export default {
  cars: [
    {
      stockNumber: 33550,
      manufacturerName: 'Skoda',
      modelName: 'Rapid',
      color: 'red',
      mileage: { number: 161468, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 34179,
      manufacturerName: 'Porsche',
      modelName: '924',
      color: 'red',
      mileage: { number: 157056, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 34909,
      manufacturerName: 'Tesla',
      modelName: 'Model X',
      color: 'red',
      mileage: { number: 130187, unit: 'km' },
      fuelType: 'Diesel',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 34979,
      manufacturerName: 'Porsche',
      modelName: 'Panamera',
      color: 'red',
      mileage: { number: 138161, unit: 'km' },
      fuelType: 'Diesel',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 35341,
      manufacturerName: 'Skoda',
      modelName: 'Forman',
      color: 'red',
      mileage: { number: 123583, unit: 'km' },
      fuelType: 'Diesel',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 35535,
      manufacturerName: 'Audi',
      modelName: 'RS 3',
      color: 'red',
      mileage: { number: 154998, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 36632,
      manufacturerName: 'Fiat',
      modelName: '124 Sport/Spider',
      color: 'red',
      mileage: { number: 141193, unit: 'km' },
      fuelType: 'Diesel',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 37153,
      manufacturerName: 'Dodge',
      modelName: 'Avenger',
      color: 'red',
      mileage: { number: 151632, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 38347,
      manufacturerName: 'Mercedes-Benz',
      modelName: 'C-Klasse',
      color: 'red',
      mileage: { number: 141775, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
    {
      stockNumber: 38792,
      manufacturerName: 'Mercedes-Benz',
      modelName: 'B-Klasse',
      color: 'red',
      mileage: { number: 174344, unit: 'km' },
      fuelType: 'Petrol',
      pictureUrl: 'http://localhost:3001/car.svg',
    },
  ],
  totalPageCount: 9,
};
